version: '3.7'

services:
  workspace:
    build:
      context: ./docker/workspace
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=8.2
        - USERNAME=${REMOTE_USER}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
    env_file: ../.env
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "3306:3306"
      - "5432:5432"
      - "6379:6379"
      - "8080:8080"
      - "8081:8081"
      - "27017:27017"
    init: true
    volumes:
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 
      - ../:/var/www
    working_dir: /var/www
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=8.2
        - USERNAME=${REMOTE_USER}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - XDEBUG_REMOTE_CONNECT_BACK=${XDEBUG_REMOTE_CONNECT_BACK}
        - XDEBUG_REMOTE_PORT=${XDEBUG_REMOTE_PORT}
    env_file: ../.env
    volumes:
      - ../:/var/www
    working_dir: /var/www
    network_mode: service:workspace

  postgres:
    build: ./docker/postgres
    env_file: ../.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
